### PR TITLE
Change commit message and author

### PR DESCRIPTION
**Pull request by aschbacd**
Change author to **GitHub Actions Bot** and change message according to [these guidelines](https://chris.beams.io/posts/git-commit/).

image

### CODE REVIEW

**Comment by Logerfo** [comment]
Thank you for you contribution. May I ask: where did the number `41898282` on the e-mail address come from?

**Comment by aschbacd** [comment]
It's the id of the GitHub Actions bot. You can see it here https://api.github.com/users/github-actions[bot].

**Comment by Logerfo** [comment]
Cool.
The change might be breaking if someone is inspecting the fields you changed for some reason, but I don't see a problem with it. If you're referencing the action master branch, you're subject to breaking changes. If you're not, you can just keep using an old version until a new feature you want comes out. Then you can refactor your inspections.
Thank you again for you contribution.

**Comment by Logerfo** [comment]
New release (0.0.3) available at https://github.com/Logerfo/newline-action/releases/tag/0.0.3 and https://github.com/marketplace/actions/newline-action.

**Pull request merged**
